### PR TITLE
Update Post.php

### PR DESCRIPTION
**Pull request by terence1990**
Allowing scopes for type and status makes the Post model friendly to users

### CODE REVIEW

**Comment by drewjbartlett** [comment]
This is great! Thank you for this!

**Comment by drewjbartlett** [comment]
@terence1990 how would you feel about adding this to the docs?

**Comment by terence1990** [comment]
@drewjbartlett yeah sure, shall i do a pull request for your README?

**Comment by drewjbartlett** [comment]
Yeah, that'd be perfect @terence1990!

**Pull request merged**
